create table users (
                       id         bigint generated by default as identity primary key,
                       name       varchar(255) not null,
                       email      varchar(255) not null unique,
                       password   varchar(255) not null,
                       role       varchar(255) not null,
                       created_at timestamp(6) with time zone not null default now(),
                       constraint users_role_check check (role in ('ADMIN', 'CUSTOMER'))
);

create table product (
                         id                 bigint generated by default as identity primary key,
                         name               varchar(255) not null,
                         slug               varchar(255) not null unique,
                         short_desc         varchar(500),
                         long_desc          varchar(4000),
                         price              numeric(10, 2) not null,
                         on_sale            boolean not null default false,
                         active             boolean not null default true,
                         discount_percent   integer,
                         stock_count        integer not null default 0,
                         created_at         timestamp(6) with time zone not null default now(),
                         category           varchar(255) not null,
                         portfolio_featured boolean not null default false,
                         constraint product_price_check    check (price >= 0),
                         constraint product_stock_check    check (stock_count >= 0),
                         constraint product_discount_check check (discount_percent is null
                             or (discount_percent > 0 and discount_percent <= 100))
);

create table product_images (
                                product_id  bigint not null,
                                image_order integer not null,
                                src         varchar(255),
                                alt         varchar(255),
                                primary key (product_id, image_order),
                                constraint fk_product_images_product
                                    foreign key (product_id) references product (id) on delete cascade
);

create table orders (
                        id             bigint generated by default as identity primary key,
                        user_id        bigint,
                        recipient_name varchar(255),
                        street         varchar(255),
                        city           varchar(255),
                        region         varchar(255),
                        postal_code    varchar(255),
                        country        varchar(255),
                        phone          varchar(255),
                        guest_email    varchar(255),
                        status         varchar(255) not null,
                        created_at     timestamp(6) with time zone not null default now(),
                        constraint orders_status_check
                            check (status in ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
                        constraint fk_orders_user
                            foreign key (user_id) references users (id) on delete restrict
);

create table order_item (
                            id         bigint generated by default as identity primary key,
                            order_id   bigint not null,
                            product_id bigint not null,
                            quantity   integer not null,
                            unit_price numeric(10, 2) not null,
                            constraint order_item_quantity_check   check (quantity > 0),
                            constraint order_item_unit_price_check check (unit_price >= 0),
                            constraint fk_order_item_order
                                foreign key (order_id) references orders (id) on delete cascade,
                            constraint fk_order_item_product
                                foreign key (product_id) references product (id) on delete restrict
);

create table address (
                         id             bigint generated by default as identity primary key,
                         user_id        bigint not null,
                         label          varchar(255),
                         recipient_name varchar(255),
                         street         varchar(255),
                         city           varchar(255),
                         region         varchar(255),
                         postal_code    varchar(255),
                         country        varchar(255),
                         phone          varchar(255),
                         is_default     boolean not null default false,
                         constraint fk_address_user
                             foreign key (user_id) references users (id) on delete cascade
);


create index idx_orders_user_id      on orders (user_id);
create index idx_orders_status       on orders (status);
create index idx_orders_created_at   on orders (created_at);
create index idx_order_item_order    on order_item (order_id);
create index idx_order_item_product  on order_item (product_id);
create index idx_product_category    on product (category);
create index idx_product_active      on product (active);
create index idx_product_portfolio   on product (portfolio_featured);
create index idx_address_user_id     on address (user_id);